In [2]:
#Sorted function in list
a=[45,67,447,77]
b=sorted(a)
print(b)

[45, 67, 77, 447]


In [5]:
#Sort function in list
a=[45,67,447,77]
a.sort()
print(a)

[45, 67, 77, 447]


In [6]:
#only Sorted function worked in tuple because it can't sorted the original tuple
a=(45,67,447,77)
b=sorted(a)
print(b)

[45, 67, 77, 447]


In [7]:
import numpy as np

In [8]:
#size manipulation functions
A= np.arange(1,13).reshape(3,4) #reshape creates an elements into matrix
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Reshape function
A1= np.arange(2,16).reshape(2,7)
print(A1)

[[ 2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15]]


In [10]:
#Another Example for reshape using linspace
A=np.linspace(2,8,10).reshape(5,2)
print(A)

[[2.         2.66666667]
 [3.33333333 4.        ]
 [4.66666667 5.33333333]
 [6.         6.66666667]
 [7.33333333 8.        ]]


In [ ]:
#reshape with 2 groups
B=np.array([23,34,54,56,78,89,45,67]).reshape(2,2,2)
print(B)

[[[23 34]
  [54 56]]

 [[78 89]
  [45 67]]]


In [ ]:
#Resize function - it changes the shape of original array
B=np.array([23,34,54,56,78,89,45,67])
B.resize(2,2,2) #Changes the shape of original array
#reshape - changes needs saving in another variable
print(B)

[[[23 34]
  [54 56]]

 [[78 89]
  [45 67]]]


In [ ]:
#array operations
# Matrix subtraction
A = np.array([34,56,78,90])
B = np.array([7,9,3,12]) #list will throw an error while arrays iterate themseleves
C = A-B
print(A-B)

[27 47 75 78]


In [ ]:
#Matrix Addition
A = np.array([34,56,78,90])
b = np.array([7,9,3,12])
C = A+B
print(C)

[ 41  65  81 102]


In [ ]:
#Matrix Multiplication (one on one)
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
C = A*B
print(C)

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
[[ 238  504]
 [ 234 1080]]


In [ ]:
#Matrix multiplication
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
C = A@B  # it calculates first row first column ,first row second column
         # And second row first column ,second row second column
print(C)

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
[[ 406  978]
 [ 816 1782]]


In [ ]:
#Matrix multiplication
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
C = A.dot(B) #Matrix multiplication similar to A@B
print(C)

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
[[ 406  978]
 [ 816 1782]]


In [ ]:
#In arrays it is not allow  strings, only allow numeric data types int,float
A=np.array([34.2,56.7,78.2,90.9,90.8])
print("Maximum is",A.max())  # returns max element in array
print("minimum is",A.min())  # returns min element in array


Maximum is 90.9
minimum is 34.2


In [ ]:
#Max Function with Axis
A = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("________________")
print(A.max(axis=0)) #axis=0 is column max number
print("________________")
print(A.max(axis=1)) #axis=1 is row maximum number

[[34 56]
 [78 90]]
________________
[78 90]
________________
[56 90]


In [ ]:
#Min Function with axis
A = np.array([34,56,78,90,16,78,32,19,14,23,97,11]).reshape(3,4)
print(A)
print("________________")
print(A.min(axis=0)) #axis=0 is column minimum number
print("________________")
print(A.min(axis=1)) #axis=1 is row minimum number

[[34 56 78 90]
 [16 78 32 19]
 [14 23 97 11]]
________________
[14 23 32 11]
________________
[34 16 11]


In [ ]:
#Joining Arrays
#Vertical stack- it join the arrays vertically(row wise)
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
print("After vertically stacking the arrays")
print(np.vstack((A,B)))  # Syntax np.vstack((a,b))

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
After vertically stacking the arrays
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
#Horizontal stack- it join the arrays horizontally(column wise)
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
print("After Horizontally stacking the arrays")
print(np.hstack((A,B)))  # Syntax np.hstack((a,b))

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
After Horizontally stacking the arrays
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
#Axis=0 is vstack function
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________")
print(B)
print("______________")
print(np.stack((B,A),axis=0)) #axis=0 in stack is vstack format

[[34 56]
 [78 90]]
______________
[[ 7  9]
 [ 3 12]]
______________
[[[ 7  9]
  [ 3 12]]

 [[34 56]
  [78 90]]]


In [ ]:
#Dimensionality stack (dstack)  colums to row shifted ,no of rows=no of groups
A= np.arange(30).reshape(2,3,5)  #(g,r,c)
print(A)
print("After dstack")
print(np.dstack(A)) #no.of rows -->no of groups g=r
#no.of column in every group --> no of rows in every group


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [12]:
#Splitting arrays vsplit is vertically split
A= np.arange(18).reshape(9,2)
print(A)
print("After splitting")
np.vsplit(A,3) #(split into equal halfs) the number is divisible by row number Ex:9rows/3= 9/3=3 splitt

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
After splitting


[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15],
        [16, 17]])]

In [16]:
#Splitting arrays vsplit is vertically split
A= np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,4)) #splitting according to your choice(it splitt before the given number)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [18]:
#Splitting arrays hsplitt is horizontal splitt
A= np.arange(20).reshape(2,10)
print(A)
print("After splitting")
np.hsplit(A,5) # number divisible by column number 10 column /5 spilt = 10/5=2

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
After splitting


[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [ ]:
#Splitting arrays hsplitt is horizontal splitt
A= np.arange(20).reshape(2,10)
print(A)
print("After splitting")
np.hsplit(A,(2,5,8)) # Splitt according to your choice (it's splitt before the given number)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
After splitting


[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4],
        [12, 13, 14]]),
 array([[ 5,  6,  7],
        [15, 16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [20]:
#argmax function- it returns the position of maximum element in array it starts from 0
A=np.arange(1,19).reshape(3,6)
print(A)
print(A.argmax())  # index of highest 18 number is 17

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
17


In [ ]:
# argmax in axis=0(column)
A= np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis=0)) #it returns max number position in every column(starts from 0)

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[2 2 1 0]


In [ ]:
# argmax in axis=1(row)
A= np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis=1)) #it returns max number position in every row(starts from 0)

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[3 2 1]


In [ ]:
#argmin function- it returns the position of minimum element in array it starts from 0
A=np.arange(1,19).reshape(3,6)
print(A)
print(A.argmin()) #index of lowest element 1 is 0

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
0


In [ ]:
# argmin in axis=0(column)
A= np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis=0)) #it returns min number position in every column(starts from 0)

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2 2]


In [ ]:
# argmin in axis=1(row)
A= np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis=1)) #it returns min number position in every row(starts from 0)

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2]


In [ ]:
#Statistical Functions
#Mean , Median, std(standard deviation),variance(var){write fomulas in documentation}
A= np.array([12,34,25,66,71,88])
print("Mean is",np.mean(A))
print("Median is",np.median(A))
print("Variance is",np.var(A))
print("Standard deviation is",np.std(A))


Mean is 49.333333333333336
Median is 50.0
Variance is 743.888888888889
Standard deviation is 27.274326552435515


In [ ]:
#Trignometry
A=np.pi
print(A) #radians

3.141592653589793


In [ ]:
 #convert radians to degree
 np.rad2deg(A)



180.0

In [ ]:
#randians and degreee
A= np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print("In radians is:",A)
print("In degrees is",np.rad2deg(A)) #Syntax = rad2deg(Array_name)

In radians is: [0.78539816 1.04719755 1.57079633 3.14159265]
In degrees is [ 45.  60.  90. 180.]


In [ ]:
# convert degrees into radians
c=np.array([0,45,60,90,120,180])
print("In radians is",np.deg2rad(A)) #conversion degree to radian Syntax= deg2rad(Array_name)

In radians is [0.01370778 0.01827705 0.02741557 0.05483114]


In [ ]:
#print sin ,cos,tan,sec,cosec values
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))
print(np.arctan(c)) #tan^-1
print(np.arccos(c)) #cos^-1
print(np.arcsin(c)) #sin^-1

[ 0.          0.85090352 -0.30481062  0.89399666  0.58061118 -0.80115264]
[ 1.          0.52532199 -0.95241298 -0.44807362  0.81418097 -0.59846007]
[ 0.          1.61977519  0.32004039 -1.99520041  0.71312301  1.33869021]
[0.         1.54857776 1.5541312  1.55968567 1.56246319 1.56524083]
[1.57079633        nan        nan        nan        nan        nan]
[ 0. nan nan nan nan nan]


<ipython-input-94-db6631a2c3d4>:6: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(c)) #cos^-1
<ipython-input-94-db6631a2c3d4>:7: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(c)) #sin^-1


In [ ]:
#some checkings
print(np.arctan(1))
print(np.arccos(1/2))
print(np.arcsin(3/4))


0.7853981633974483
1.0471975511965979
0.848062078981481


In [ ]:
#hyotneuse function
a=8
b=6
print(np.hypot(a,b))

10.0


In [ ]:
#Searching an element in array using where and condition it
A= np.array([90,3,45,21,34,90,21]) # returns the index position of searching element(It starts from Zero)
print(np.where(A==3))
print(np.where(A==21))  #Equality
print(np.where(A%2==0)) #Even numbers
print(np.where(A>50))   #we use any conditions after where



(array([1]),)
(array([3, 6]),)
(array([0, 4, 5]),)
(array([0, 5]),)


In [ ]:
#Read an array with one dimension(Searchsorted function)
import numpy as np
A=np.array([1,2,3,4])
print(np.searchsorted(A,4))

3


In [ ]:
#operations between two arrays
A=np.array([6,24,60,12,18])
B= np.array([3,1,5,9,4])
print(np.add(A,B))
print([np.subtract(A,B)])
print([np.divide(A,B)])
print(np.mod(A,B))

[ 9 25 65 21 22]
[array([ 3, 23, 55,  3, 14])]
[array([ 2.        , 24.        , 12.        ,  1.33333333,  4.5       ])]
[0 0 0 3 2]


In [ ]:
#sort function- sort the elements in the given array
A=np.array([6,24,60,12,18])
print(np.sort(A))

[ 6 12 18 24 60]


In [ ]:
#Difference function- it subtract second number with first number third number with second number........
A=np.array([6,24,60,12,18])
print(np.diff(A))

[ 18  36 -48   6]


In [ ]:
#Set operations in array
# union   (union1d)
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 18 24 60]


In [ ]:
# Set Difference  (setdiff1d)
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [ ]:
# Set intersection  (intersect1d)
A=np.array([6,24,60,12,18])
B=np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


In [22]:
#Round Functions
#1)trunc function
a1=np.trunc([-3.1666,3.6667])
print(a1)

[-3.  3.]


In [ ]:
#2)fix function
a1=np.fix([-3.1666,3.6667])
print(a1)

[-3.  3.]


In [27]:
#3)around function
a1=np.around([-3.1666,4.1])
print(a1)

[-3.  4.]


In [31]:
#4)floor function - it rounds the value to starting value for negative values it is reversed
a1=np.floor([-3.1666,3.9667])
print(a1)

[-4.  3.]


In [ ]:
#5)ceil function - it rounds the value to ending value for nagative it is reversed
a1=np.ceil([-3.9666,3.1])
print(a1)

[-3.  4.]


In [ ]:
#Round Functions used in array
A=np.array([4.1,-4.51])
print(np.fix(A))
print(np.floor(A))
print(np.ceil(A))

[ 4. -4.]
[ 4. -5.]
[ 5. -4.]


In [ ]:
#Cummulative sum Function- it adds the first number with second number then second number with third........
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [ ]:
#Cummulative product Function- it products the first number with second then second number with third........
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [ ]:
# LCM and GCD Functions
print(np.lcm(34,56))
print(np.gcd(445,665))




952
5


In [ ]:
#reduce Function - reduces arrays dimension by one by applying ufunc along one axis
Ar=np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [ ]:
Ar=np.array([45,65,30])
print(np.gcd.reduce(Ar))

5


In [ ]:
#Inverse Function
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Random in Numpy package
from numpy import random as rd

In [ ]:
#Random functions
#rand() function
A=rd.rand() #limit 0 to 0.99
print(A)

0.2774169149289797


In [ ]:
A=rd.rand(10) #Print 10 numbers limits 0 to 0.99
print(A)

[0.82736274 0.88717785 0.52270352 0.79821571 0.46275886 0.51830798
 0.7842167  0.81802975 0.73513883 0.55477677]


In [ ]:
#randint Function
a=rd.randint(4) #randlimit-->0,1,2,3
print(a)        #print only one number between 4 numbers


2


In [ ]:
#Random numbers print using size function
A=rd.randint(50,size=6) #size is the no of numbers print
B=rd.randint(50,size=(2,3))
print(A)
print("_______")
print(B)

[45 21 37 36  4 36]
_______
[[45  4 21]
 [18 28 13]]


In [ ]:
#Joints Functions
# 1)Inner function- #multiply first element in first array to first element in second array then sum
A=np.array([1,2,3]) #multiply second element in first array to second element in second array then sum....
B=np.array([4,5,6])
# 1*4 + 2*5 + 3*6
print(np.inner(A,B))

32


In [ ]:
#2)Outer function - it multiplies  first number in first array with all numbers in second array then sum
                   #multiplies second number in first array with all numbers in second array then sum...
A=np.array([1,2,3])
B=np.array([4,5,6])
# 1*(4,5,6) 2*(4,5,6) 3*(4,5,6)
print(np.outer(A,B))


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#3)Cross function - it is same as (ad-bc) det value format
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))

[-3  6 -3]
