In [ ]:
#display the integer in string
a=10
print("iam", a,"years old")

iam 10 years old


In [ ]:
#adding two numbers
a=int(input("Enter the a number:"));
b=int(input("Enter the b number:"));
print("Sum is",a+b);
print("Differnce is",a-b);
print("Product is",a*b);
print("Dvision is",a/b);
print("Exponent is",a**b);
print("Modulus is",a%b);
print("Floor division is", a//b);

Enter the a number:5
Enter the b number:6
Sum is 11
Differnce is -1
Product is 30
Dvision is 0.8333333333333334
Exponent is 15625
Modulus is 5
Floor division is 0


In [1]:
#take a number from the user which is a salary if the salary is more than 50000 their is a 10% tax deduction print the reamaing salary
a=int(input("Enter the salary:"))
if(a>=50000):
  print("salary after tax is:",(a-a*10/100));       #tax=a*10/100 ,(a-tax)
else:
  print("salary is less than 50000 no tax deducted");




Enter the salary:40000
salary is less than 50000 no tax deducted


In [ ]:
#take the number from the user and satisfy the below conditions
# sal is 0 to 50000 5% reduction,50000 to 70000 10% reduction,
# 70000 to 100000 12% reduction above 1L next level promoted
a=int(input("Enter the Salary:"))
if(a>=0 and a<50000):
  print("tax applied 5%",a-(a*5/100))
elif(a>=50000 and a<70000):
  print("tax applied 10%",a-(a*10/100))
elif(a>=70000 and a<100000):
  print("tax applied 12%",a-(a*12/100))
else:
  print("sal is more next level promoted")



Enter the Salary:60000
tax applied 10% 54000.0


In [ ]:
n=int(input("Enter the value:"));
i=1;
range=int(input("Enter the range:"));
while(i<=range):
  print(n,'x',i,'=',n*i);
  i+=1;


Enter the value:6
Enter the range:10
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


In [ ]:
#for loop
n=int(input("Enter the Number:"));

for i in range(1,11,1):

    print( n ,'x', i , '=',n*i);


Enter the Number:5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
#list
l1=[1,"GOPI",68,9.6,True];
for i in l1:
  print(i);


1
GOPI
68
9.6
True


In [ ]:
#lists are mutable
l1.append("Dhanush"); #adds element at back of the list
print(l1);
l1.insert(4,"Mango"); #listname.insert(index,element)
print(l1);

[1, 'GOPI', 68, 9.6, True, 'Dhanush']
[1, 'GOPI', 68, 9.6, 'Mango', True, 'Dhanush']


In [ ]:
#Extend
l2=["puppy","berry"]
l1.extend(l2); #l1=l1+l2
print(l1);

[1, 'GOPI', 68, 9.6, 'Mango', True, 'Dhanush', 'puppy', 'berry']


In [ ]:
#Listname.pop(index)
l1.pop(2);
print(l1);
l1.remove('berry');
print(l1);

[1, 'GOPI', 'Mango', True, 'Dhanush', 'puppy', 'berry']
[1, 'GOPI', 'Mango', True, 'Dhanush', 'puppy']


In [ ]:
#create a list of 10 random integer  elements ,print their squares save these squares to new list
l1=[23,34,45,38,12,456];
l3=[];
for i in l1:
  l3.append(i*i);
print(l3);

[529, 1156, 2025, 1444, 144, 207936]


In [ ]:
#list comprehension
#newlist = [output for]
l1=[23,34,45,38,12,456];
l2=[i*i for i in l1];
print(l2);



[529, 1156, 2025, 1444, 144, 207936]


In [ ]:
#list comprehension
#newlist = [output for if con]
l1=[23,34,45,38,12,67,456];
l2=[i*i for i in l1 if i>50];
print(l2);

[4489, 207936]


In [ ]:
#list comprehension
#newlist = [(st of if)if (cond) else(st of else) for]
l1=[23,95,38,167,456];
l2=[(i*i) if (i>50) else ('X') for i  in l1 ];
print(l2);

['X', 9025, 'X', 27889, 207936]


In [ ]:
#take the salary from the user if the salary is less than 15k 10% tax otherwise 15% tax
a=[78000,50400,34000,23000,14000];
list=[(i-(i*10/100)) if i<50000 else (i-(i*15/100)) for i in a];
print(list);


[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Dictionary:
dictname={key1:val1,key2:val2.....}

In [ ]:
#Create
dict1={"Mentor":'jwalitha',34:'likitha',35:'Ramya',37:'Lavanya',58:'Dhanush'}
print(dict1);

{'Mentor': 'jwalitha', 34: 'likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}


In [ ]:
#Create
dict1={"Mentor":'jwalitha',"Mentor":'likitha',35:'Ramya',37:'Lavanya',58:'Dhanush'}
print(dict1);


{'Mentor': 'likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}


In [ ]:
print(dict1.keys())  #Displays all values in dictionary
print(dict1.values()) #Displays all values in dictionary

dict_keys(['Mentor', 35, 37, 58])
dict_values(['likitha', 'Ramya', 'Lavanya', 'Dhanush'])


In [ ]:
#Create
dict1={"Mentor":'jwalitha',34:'likitha',35:'Ramya',37:'Lavanya',58:'Dhanush'}
print(dict1[37])#display the single value


Lavanya


In [ ]:
dict3={"Dept":"CSE","details":{"year":"II","Sec":"D","Count":71}} #dictionary inside dictionary
print(dict3["details"]["Sec"])
print("Year is",dict3["details"]["year"])
print("section is",dict3["details"]["Sec"])
print("Count is",dict3["details"]["Count"])


D
Year is II
section is D
Count is 71


In [ ]:
id=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","Mani"]
new_zip=(zip(id,name))
for i in new_zip:
  print(i);


(34, 'Joe')
(56, 'Suji')
(78, 'Rohini')
(39, 'Shankar')
(100, 'Mani')


In [ ]:
id=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","Mani"]
new_zip=(zip(id,name))
print(dict(new_zip))

{34: 'Joe', 56: 'Suji', 78: 'Rohini', 39: 'Shankar', 100: 'Mani'}


In [ ]:
#Numpy
import numpy as np
A=np.array([1,2,3,4]) #one dimensional array
print(A.ndim)   # check the dimension of array
print(A.shape)

1
(4,)


In [ ]:
B=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #Two Dimensional array
#Elements in each roe=columns
print(B)
print(B.ndim)
print(B.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
C=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])# three dimensional array
#Elements in each row=columns
print(C)
print(C.ndim)
print(C.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(2, 3, 3)


In [ ]:
A1=np.ones((3,4)) # np.ones((groups,rows,colums))
print(A1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A1=np.zeros((2,3,4)) # np.zeros((groups,rows,colums))
print(A1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
A1=np.eye(4) #np.eye(identity value)
print(A1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2) # Start,stop,steps
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers divisible by 8 using arange function between 1 and 1000
A2=np.arange(8,1001,8)
print(A2)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
A=np.linspace(48,59,10) # linspace spilting a range into n numbers with common differences
print(A)


[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
#tuples
tup=(12,43,6,55,'apple')
for i in tup: #Display elements in the tuples using loop
  print(i)


12
43
6
55
apple


In [ ]:
print(tup) #Original array
print(tup[::-1]) # Tuple slicing reverse

(12, 43, 6, 55, 'apple')
('apple', 55, 6, 43, 12)


In [ ]:
#operation functions
t=(21,56,4,23,12)
s=sorted(t) #sorted in tuple
print(s)
s.pop() #pop
print(s)
s.pop(2) #using index
print(s)

[4, 12, 21, 23, 56]
[4, 12, 21, 23]
[4, 12, 23]


In [ ]:
#Concatnation of tuples
print(t+t)

(21, 56, 4, 23, 12, 21, 56, 4, 23, 12)


In [ ]:
#convert list to tuple
l1=[12,3,45,67,88,89]
print(l1)
p=tuple(l1)
print(p)

[12, 3, 45, 67, 88, 89]
(12, 3, 45, 67, 88, 89)


In [ ]:
#tuple comprehension
t=(1,23,55,67,88,99,22,23,55)
l=[i for i in t if i%11==0]
p=tuple(l)
print(p)

(55, 88, 99, 22, 55)


In [ ]:
print(t.count(23))

2


In [ ]:
print(max(t)) # maximum elements
print(min(t)) # minimum elements

99
1


In [ ]:
#sets
s1={1,23,45,1,23,67,89}  #sets are mutable elements
print(s1)

{1, 67, 23, 89, 45}


In [ ]:
s2={1,23,1,67,89}
print(s1.union(s2)) #union

{1, 67, 45, 23, 89}


In [ ]:
print(s2.intersection(s1)) #intersection

{89, 67, 1, 23}


In [ ]:
print(s1.difference(s2)) # difference

{45}


In [ ]:
s1.update(s2) #update 
print(s1)

{1, 67, 45, 23, 89}


In [ ]:
s1.add(234) #add
print(s1)

{1, 67, 234, 45, 23, 89}


#tuples and sets
#Documentation upto today
#Qr code